deploy:
  provider: heroku
  api_key:
    secure: o3BbTfy8IHSRp0+Bs2BJSsIZ7EpSYXFW4EdP8/i+bA75BdqTTY6K4tJ0/lGvv7wkCSTg4/82A39Y/Juglplyk5+fbtOul6AE2EqljOsuD+/2+Le60a/AWDOHBCyhWogLHPeHXbtC4gOoj//OVjWTSqkda6D+71gwyviNWKH0nnLnUoLXTdLfhNhjP3zJgPJrMMIViIbMoI8RvrVLLAOm1LWv8Bp9bIVTnaEDQE6fm88I/RkjMPiyX0/x8s3DVsN4c6c/HmyO6+ULsxMCpj5WlcX3a5RUT8ub9NoZbPKb+F0/DqE0+JW+xM2yjccQSP6IHKGxTlfR8DuZFL191+YWB6gCE+z1thXkX8kicvPMsMeBP1pdETIAQDBpmMAwFYTmITcRrlzfkYyPCMBcnXj5l2CGVh3hEIvSTc6oiOTfrm3H78DNNz6rhlWXe+0IPQFiTd3CtmjJgJTND4qvaOGWud2AfXUV5MOs/9qrHRp9Ep9PXoWjWAF2MRJ/5nusz4//UKEOx3AASVgUJUDN5EgthRB43TrCrIZG6B4EI0V5xG0Qh4/kZO6rTEsc914p7hssIKvoIbXwnOlDQi9HYXuoOOlgs0gyy2laSMeVOwT27+ji+kkED47d75of5MWAUnNdGHxUnctFkGA0EvcAAPe8bGLqoe3SF96XZIBQLB+hGZY=
  strategy: git
  on:
    repo: TJaakkola/BeachPoints
